### ISSUE TITLE
Link to a Module's definitions when clicking on extensions

### ISSUE THREAD

**Issue by dimitribouniol** [tayloraswift/swift-unidoc#373]
Following up from [slack](https://swift-open-source.slack.com/archives/C04B8HURKB4/p1734540882827429?thread_ts=1734514990.561699&cid=C04B8HURKB4), when clicking on an extension defined in one module, the link to the type page should automatically scroll to that module's definitions.

For instance, clicking on `WebPushManager` `https://swiftinit.org/hist/mochidev.swift-webpush:main/webpush/webpushmanager` from `https://swiftinit.org/hist/mochidev.swift-webpush:main/webpushtesting`'s sidebar should link to `https://swiftinit.org/hist/mochidev.swift-webpush:main/webpush/webpushmanager#se:WebPushTesting` instead of `https://swiftinit.org/hist/mochidev.swift-webpush:main/webpush/webpushmanager`

**Comment by tayloraswift** [comment]
this was deployed to prod (swiftinit.org) overnight

**Comment by dimitribouniol** [comment]
Thanks!
